//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.tblNews {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txttitle;
		protected global::System.Web.UI.WebControls.TextBox txtcontent;
	protected global::System.Web.UI.WebControls.Label lblpubdate;
		protected global::System.Web.UI.WebControls.TextBox txtkeyword;
		protected global::System.Web.UI.WebControls.TextBox txtisindex;
		protected global::System.Web.UI.WebControls.TextBox txtisenable;
		protected global::System.Web.UI.WebControls.TextBox txttype;
		protected global::System.Web.UI.WebControls.TextBox txtviewcounts;
		protected global::System.Web.UI.WebControls.TextBox txtareaid;
		protected global::System.Web.UI.WebControls.TextBox txtfilesrc;
		protected global::System.Web.UI.WebControls.TextBox txtneednum;
		protected global::System.Web.UI.WebControls.TextBox txtdownloadnum;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
