//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.tblNews {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lbltitle;
	protected global::System.Web.UI.WebControls.Label lblcontent;
	protected global::System.Web.UI.WebControls.Label lblpubdate;
	protected global::System.Web.UI.WebControls.Label lblkeyword;
	protected global::System.Web.UI.WebControls.Label lblisindex;
	protected global::System.Web.UI.WebControls.Label lblisenable;
	protected global::System.Web.UI.WebControls.Label lbltype;
	protected global::System.Web.UI.WebControls.Label lblviewcounts;
	protected global::System.Web.UI.WebControls.Label lblareaid;
	protected global::System.Web.UI.WebControls.Label lblfilesrc;
	protected global::System.Web.UI.WebControls.Label lblneednum;
	protected global::System.Web.UI.WebControls.Label lbldownloadnum;


       
    }
}
