//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.tblBeike {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lbllevel;
	protected global::System.Web.UI.WebControls.Label lblareaid;
	protected global::System.Web.UI.WebControls.Label lblsubjectid;
	protected global::System.Web.UI.WebControls.Label lblname;
	protected global::System.Web.UI.WebControls.Label lblviewcount;
	protected global::System.Web.UI.WebControls.Label lblpubdate;
	protected global::System.Web.UI.WebControls.Label lblisjing;
	protected global::System.Web.UI.WebControls.Label lblisgaokao;
	protected global::System.Web.UI.WebControls.Label lblisdujia;


       
    }
}
