//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.webusers {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtusername;
		protected global::System.Web.UI.WebControls.TextBox txtpassword;
		protected global::System.Web.UI.WebControls.TextBox txtemail;
		protected global::System.Web.UI.WebControls.TextBox txtschool;
		protected global::System.Web.UI.WebControls.TextBox txtname;
		protected global::System.Web.UI.WebControls.TextBox txtmobile;
		protected global::System.Web.UI.WebControls.TextBox txtprovince;
		protected global::System.Web.UI.WebControls.TextBox txtcity;
		protected global::System.Web.UI.WebControls.TextBox txtposition;
		protected global::System.Web.UI.WebControls.TextBox txtsubject;
		protected global::System.Web.UI.WebControls.TextBox txtaddress;
		protected global::System.Web.UI.WebControls.TextBox txttel;
		protected global::System.Web.UI.WebControls.TextBox txtlevel;
		protected global::System.Web.UI.WebControls.TextBox txtregdate;
		protected global::System.Web.UI.WebControls.TextBox txtip;
		protected global::System.Web.UI.WebControls.TextBox txtdaoqidate;
		protected global::System.Web.UI.WebControls.TextBox txtopenpwd;
		protected global::System.Web.UI.WebControls.TextBox txtyewu;
		protected global::System.Web.UI.WebControls.TextBox txtprovinceid;
		protected global::System.Web.UI.WebControls.TextBox txtcityid;
		protected global::System.Web.UI.WebControls.TextBox txtgrade;
		protected global::System.Web.UI.WebControls.TextBox txtstatus;
		protected global::System.Web.UI.WebControls.TextBox txtyewudiqv;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
