//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.webusers {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblusername;
	protected global::System.Web.UI.WebControls.Label lblpassword;
	protected global::System.Web.UI.WebControls.Label lblemail;
	protected global::System.Web.UI.WebControls.Label lblschool;
	protected global::System.Web.UI.WebControls.Label lblname;
	protected global::System.Web.UI.WebControls.Label lblmobile;
	protected global::System.Web.UI.WebControls.Label lblprovince;
	protected global::System.Web.UI.WebControls.Label lblcity;
	protected global::System.Web.UI.WebControls.Label lblposition;
	protected global::System.Web.UI.WebControls.Label lblsubject;
	protected global::System.Web.UI.WebControls.Label lbladdress;
	protected global::System.Web.UI.WebControls.Label lbltel;
	protected global::System.Web.UI.WebControls.Label lbllevel;
	protected global::System.Web.UI.WebControls.Label lblregdate;
	protected global::System.Web.UI.WebControls.Label lblip;
	protected global::System.Web.UI.WebControls.Label lbldaoqidate;
	protected global::System.Web.UI.WebControls.Label lblopenpwd;
	protected global::System.Web.UI.WebControls.Label lblyewu;
	protected global::System.Web.UI.WebControls.Label lblprovinceid;
	protected global::System.Web.UI.WebControls.Label lblcityid;
	protected global::System.Web.UI.WebControls.Label lblgrade;
	protected global::System.Web.UI.WebControls.Label lblstatus;
	protected global::System.Web.UI.WebControls.Label lblyewudiqv;


       
    }
}
