//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.tblKejian {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lbllevel;
	protected global::System.Web.UI.WebControls.Label lblsubjectid;
	protected global::System.Web.UI.WebControls.Label lblversionid;
	protected global::System.Web.UI.WebControls.Label lblname;
	protected global::System.Web.UI.WebControls.Label lbluploadtime;
	protected global::System.Web.UI.WebControls.Label lblfilesrc;
	protected global::System.Web.UI.WebControls.Label lbldownloadnum;
	protected global::System.Web.UI.WebControls.Label lblneednum;
	protected global::System.Web.UI.WebControls.Label lblextension;
	protected global::System.Web.UI.WebControls.Label lblyear;
	protected global::System.Web.UI.WebControls.Label lbluploader;
	protected global::System.Web.UI.WebControls.Label lblcontent;
	protected global::System.Web.UI.WebControls.Label lblprepareid;
	protected global::System.Web.UI.WebControls.Label lblisjing;
	protected global::System.Web.UI.WebControls.Label lblisgaokao;
	protected global::System.Web.UI.WebControls.Label lblisdujia;
	protected global::System.Web.UI.WebControls.Label lblbeikao;


       
    }
}
