//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.tblzhuanti {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtname;
		protected global::System.Web.UI.WebControls.TextBox txtpicsrc;
		protected global::System.Web.UI.WebControls.TextBox txtftitle;
		protected global::System.Web.UI.WebControls.TextBox txtstitle;
		protected global::System.Web.UI.WebControls.TextBox txtdaodu;
		protected global::System.Web.UI.WebControls.TextBox txtmodel;
		protected global::System.Web.UI.WebControls.TextBox txtviewstate;
		protected global::System.Web.UI.WebControls.TextBox txtlevel;
		protected global::System.Web.UI.WebControls.TextBox txtsubject;
		protected global::System.Web.UI.WebControls.TextBox txtcategory;
		protected global::System.Web.UI.WebControls.TextBox txtistop;
		protected global::System.Web.UI.WebControls.TextBox txtposition;
		protected global::System.Web.UI.WebControls.TextBox txtbigpic;
		protected global::System.Web.UI.WebControls.TextBox txtupdatetime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
