//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.tblzhuanti {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblname;
	protected global::System.Web.UI.WebControls.Label lblpicsrc;
	protected global::System.Web.UI.WebControls.Label lblftitle;
	protected global::System.Web.UI.WebControls.Label lblstitle;
	protected global::System.Web.UI.WebControls.Label lbldaodu;
	protected global::System.Web.UI.WebControls.Label lblmodel;
	protected global::System.Web.UI.WebControls.Label lblviewstate;
	protected global::System.Web.UI.WebControls.Label lbllevel;
	protected global::System.Web.UI.WebControls.Label lblsubject;
	protected global::System.Web.UI.WebControls.Label lblcategory;
	protected global::System.Web.UI.WebControls.Label lblistop;
	protected global::System.Web.UI.WebControls.Label lblposition;
	protected global::System.Web.UI.WebControls.Label lblbigpic;
	protected global::System.Web.UI.WebControls.Label lblupdatetime;


       
    }
}
