//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.page_dict {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblPAGEID;
		protected global::System.Web.UI.WebControls.TextBox txtPAGENAME;
		protected global::System.Web.UI.WebControls.TextBox txtPAGEPARENTID;
		protected global::System.Web.UI.WebControls.TextBox txtPAGEURL;
		protected global::System.Web.UI.WebControls.TextBox txtPAGETARGET;
		protected global::System.Web.UI.WebControls.TextBox txtPAGEIMG;
		protected global::System.Web.UI.WebControls.TextBox txtCHECKFLAG;
		protected global::System.Web.UI.WebControls.TextBox txtPAGEMOUDAL;
		protected global::System.Web.UI.WebControls.TextBox txtISFLAG;
		protected global::System.Web.UI.WebControls.TextBox txtSEQSORT;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
