//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.page_dict {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblPAGEID;
	protected global::System.Web.UI.WebControls.Label lblPAGENAME;
	protected global::System.Web.UI.WebControls.Label lblPAGEPARENTID;
	protected global::System.Web.UI.WebControls.Label lblPAGEURL;
	protected global::System.Web.UI.WebControls.Label lblPAGETARGET;
	protected global::System.Web.UI.WebControls.Label lblPAGEIMG;
	protected global::System.Web.UI.WebControls.Label lblCHECKFLAG;
	protected global::System.Web.UI.WebControls.Label lblPAGEMOUDAL;
	protected global::System.Web.UI.WebControls.Label lblISFLAG;
	protected global::System.Web.UI.WebControls.Label lblSEQSORT;


       
    }
}
