//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.tblancient {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txttitle;
		protected global::System.Web.UI.WebControls.TextBox txtcontent;
		protected global::System.Web.UI.WebControls.TextBox txtpubdate;
		protected global::System.Web.UI.WebControls.TextBox txtkeyword;
		protected global::System.Web.UI.WebControls.TextBox txtviewcounts;
		protected global::System.Web.UI.WebControls.TextBox txtfirst_id;
		protected global::System.Web.UI.WebControls.TextBox txtsecond_id;
		protected global::System.Web.UI.WebControls.TextBox txtthird_id;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
