//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.tblWebinfo {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtname;
		protected global::System.Web.UI.WebControls.TextBox txtlogosrc;
		protected global::System.Web.UI.WebControls.TextBox txtfootinfo;
		protected global::System.Web.UI.WebControls.TextBox txtheadseo;
		protected global::System.Web.UI.WebControls.TextBox txtkeyseo;
		protected global::System.Web.UI.WebControls.TextBox txtdescribseo;
		protected global::System.Web.UI.WebControls.TextBox txtweixin;
		protected global::System.Web.UI.WebControls.TextBox txtweibo;
		protected global::System.Web.UI.WebControls.TextBox txtgengxin;
		protected global::System.Web.UI.WebControls.TextBox txtzongliang;
		protected global::System.Web.UI.WebControls.TextBox txtschooltestnum;
		protected global::System.Web.UI.WebControls.TextBox txtjinpintestnum;
		protected global::System.Web.UI.WebControls.TextBox txtschoolnum;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
