//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.tblWebinfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblname;
	protected global::System.Web.UI.WebControls.Label lbllogosrc;
	protected global::System.Web.UI.WebControls.Label lblfootinfo;
	protected global::System.Web.UI.WebControls.Label lblheadseo;
	protected global::System.Web.UI.WebControls.Label lblkeyseo;
	protected global::System.Web.UI.WebControls.Label lbldescribseo;
	protected global::System.Web.UI.WebControls.Label lblweixin;
	protected global::System.Web.UI.WebControls.Label lblweibo;
	protected global::System.Web.UI.WebControls.Label lblgengxin;
	protected global::System.Web.UI.WebControls.Label lblzongliang;
	protected global::System.Web.UI.WebControls.Label lblschooltestnum;
	protected global::System.Web.UI.WebControls.Label lbljinpintestnum;
	protected global::System.Web.UI.WebControls.Label lblschoolnum;


       
    }
}
