//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.tblschool {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtname;
		protected global::System.Web.UI.WebControls.TextBox txtheadname;
		protected global::System.Web.UI.WebControls.TextBox txtstar;
		protected global::System.Web.UI.WebControls.TextBox txtcontent;
		protected global::System.Web.UI.WebControls.TextBox txtlevel;
		protected global::System.Web.UI.WebControls.TextBox txtareaid;
	protected global::System.Web.UI.WebControls.Label lblintime;
		protected global::System.Web.UI.WebControls.TextBox txtimgsrc;
		protected global::System.Web.UI.WebControls.TextBox txtSchoolPosition;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
