//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.tbltest {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtlevel;
		protected global::System.Web.UI.WebControls.TextBox txtareaid;
		protected global::System.Web.UI.WebControls.TextBox txtsubjectid;
		protected global::System.Web.UI.WebControls.TextBox txttestcategory;
		protected global::System.Web.UI.WebControls.TextBox txttestname;
		protected global::System.Web.UI.WebControls.TextBox txtuploadtime;
		protected global::System.Web.UI.WebControls.TextBox txtfilesrc;
		protected global::System.Web.UI.WebControls.TextBox txtdownloadnum;
		protected global::System.Web.UI.WebControls.TextBox txtneednum;
		protected global::System.Web.UI.WebControls.TextBox txtextension;
		protected global::System.Web.UI.WebControls.TextBox txtyear;
		protected global::System.Web.UI.WebControls.TextBox txtuploader;
		protected global::System.Web.UI.WebControls.TextBox txtcontent;
		protected global::System.Web.UI.WebControls.TextBox txtgroupid;
		protected global::System.Web.UI.WebControls.TextBox txtschoolid;
		protected global::System.Web.UI.WebControls.TextBox txtismingxiao;
		protected global::System.Web.UI.WebControls.TextBox txtisjingpin;
		protected global::System.Web.UI.WebControls.TextBox txtistuijian;
		protected global::System.Web.UI.WebControls.TextBox txtisgaokao;
		protected global::System.Web.UI.WebControls.TextBox txtisdujia;
		protected global::System.Web.UI.WebControls.TextBox txtbeikao;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
